### ISSUE TITLE
Using Map with PlutusTx.Rational causes the model checker to wig out.

### ISSUE THREAD

**Issue by locallycompact** [input-output-hk/plutus-apps#100]
Hi, If I have a ContractModel such as

```
instance ContractModel FooModel where
  data Action FooModel = Start Wallet
                           | Next (Map.Map Integer PlutusTx.Rational)
```

then when the model fails I get an unreadable exception

```
*** Failed! (after 5 tests and 2 shrinks):
Exception:
  This must be replaced by the core-to-plc plugin during compilation: error
  CallStack (from HasCallStack):
    error, called at src/PlutusTx/Utils.hs:7:26 in plutus-tx-0.1.0.0-7T7T1MDlfuyAAfoB0wf3gv:PlutusTx.Utils
Exception thrown while showing test case:
  This must be replaced by the core-to-plc plugin during compilation: error
  CallStack (from HasCallStack):
    error, called at src/PlutusTx/Utils.hs:7:26 in plutus-tx-0.1.0.0-7T7T1MDlfuyAAfoB0wf3gv:PlutusTx.Utils
```

Notably, this does not happen if the Action is defined using just PlutusTx.Rational, or using Map for some other value type that is not PlutusTx.Rational. In those cases the model checker runs normally and I observe normal contract model errors. Only when a Map contains a Rational do I get this trace in the test.

**Comment by ak3n** [comment]
>This must be replaced by the core-to-plc plugin during compilation: error

This exception is happens when on-chain code is called in off-chain code and is raised by [`error`](https://github.com/input-output-hk/plutus/blob/26d2c4fe63d76dc56c56801e8e7a20cb1de2d4a4/plutus-tx/src/PlutusTx/Builtins/Internal.hs#L65) function.

Please check what `PlutusTx` functions you are trying to use in usual Haskell code. Or you might need to mark on-chain function with `INLINABLE` pragma to compile it properly.
