### ISSUE TITLE
Prebuilt binaries for PAB and ChainIndex for Mac M1

### ISSUE THREAD

**Issue by Uli999** [input-output-hk/plutus-apps#140]
## Area

[] *Plutus Foundation* Related to the GHC plugin, Haskell-to-Plutus compiler, on-chain code
[x] *Plutus Application Framework* Related to the Plutus application backend (PAB), emulator, Plutus libraries
[] *Marlowe* Related to Marlowe
[] *Other* Any other topic (Playgrounds, etc.)

## Describe the feature you'd like

Due to ongoing compilation problems with Mac M1 it would be very helpful to get prebuilt binaries for PAB and ChainIndex for Mac M1 for testing.

**Comment by ak3n** [comment]
Thanks for the issue!

Currently PAB releases don't provide prebuilt binaries for any platform. It's not stable yet and they are marked as "pre-release".

Also, the problem of getting prebuilt binaries might be complicated due to ongoing compilation problems. The support of M1 is not in current milestones as far as I know and is up to community at the moment.
