### ISSUE TITLE
AesonException "Error in $.walletServerConfig:

### ISSUE THREAD

**Issue by Uli999** [input-output-hk/plutus-apps#151]
## Summary
Following the steps in the test-node scenario I'm getting the following error, when trying to start the pab.

plutus-pab-examples: AesonException "Error in $.walletServerConfig: parsing Cardano.Wallet.Types.WalletConfig failed, expected Object with key \"tag\" containing one of [\"LocalWalletConfig\",\"RemoteWalletConfig\"], key \"tag\" not found"

<img width="1429" alt="image" src="https://user-images.githubusercontent.com/13240404/143764376-b952e995-9b53-459a-b4a0-e936fbc590d3.png">

## Steps to reproduce

1. Start node, wait until synced
2. Start wallet server, wait until synced
3. Start chainindex, wait until synched
4. Create and load Wallet and export Wallet_ID
5. Trying to start PAB with  cabal exec -- plutus-pab-examples \
  --config testnet/pab-config.yml migrate
or cabal exec -- plutus-pab-examples \
  --config testnet/pab-config.yml webserver \
  --passphrase pab123456789 

## Expected behavior

PAB starts und runs

## System info (please complete the following information):

- OS: [MacOS Intel based]
- Version [11.4 BigSur]
- cloned 25.11.2021 15:20

## Screenshots and attachments

<img width="404" alt="image" src="https://user-images.githubusercontent.com/13240404/143764808-7987b2f4-b24a-489f-92ae-fd06d40d7d29.png">

**Comment by bhoudebert** [comment]
Hi,

Yes you are not aligned with recent updates on wallet configuration.

Here have a look: https://github.com/input-output-hk/plutus-apps/blob/main/plutus-pab/plutus-pab.yaml.sample

You will see a new info has popped out in the walletServerConfig (mostly due to a new PR provided possible remote of a wallet).

NB: for ease I strongly recommend you to mention commit instead of time, also be aware that using main branch is more unstable than using a tag or a prerelease/beta of PAB.

**Comment by Uli999** [comment]
Hi,
thanks for the hint. I'll try this. Maybe it would be helpful to update the mentioned pab-config.yml file of the scenario regarding this to avoid more confusion.
cabal exec -- plutus-pab-examples 
--config **testnet/pab-config.yml** webserver

**Comment by silky** [comment]
Yes, thanks @Uli999 for reporting!
