### ISSUE TITLE
Use of forwardingMintingPolicy gives a Currency Symbol different to ownCurrencySymbol

### ISSUE THREAD

**Issue by georgeos** [input-output-hk/plutus-apps#3]
## Area

[] *Plutus Foundation* Related to the GHC plugin, Haskell-to-Plutus compiler, on-chain code
[*] *Plutus Application Framework* Related to the Plutus application backend (PAB), emulator, Plutus libraries
[] *Marlowe* Related to Marlowe
[] *Other* Any other topic (Playgrounds, etc.)

## Summary

When `forwardingMintingPolicy` or `mkForwardingMintingPolicy` is used to mint, comparation between ownCurrencySymbol and the currency symbol minted fails, therefore rejects the transaction.

## Steps to reproduce

1. Forward validations of a minting policy to a validator script
`mintPolicy :: MintingPolicy`
`mintPolicy = forwardingMintingPolicy myTypedValidator`

2. Validate the currency symbol from onchain code
`checkMintedAmount :: Bool`
`checkMintedAmount = case flattenValue (txInfoMint info) of`
`          [(cs, tn', amt)] -> ownCurrencySymbol ctx == cs && tn' == tn && amt == 1`
`          _ -> False`

3. See error:
`"WalletError (ValidationError (ScriptFailure (EvaluationError [\"Lh\"] \"CekEvaluationFailure\")))"`

## Expected behavior

Successful validation of ownCurrencySymbol vs currency symbol minted

## System info (please complete the following information):

- Plutus version or commit hash: 547e22a975d9b688ad2121f56e63691bead661cc

**Comment by ak3n** [comment]
Sorry for the late reply!

Turned out yes, it's not possible to use `ownCurrencySymbol` in the validator because it requires `ScriptPurpose=Minting` which is true only in case of `MintingPolicy`. Validators work with `ScriptPurpose=Spending`.

For example, `ThreadToken` (from `StateMachine`) uses `ownCurrencySymbol` in `MintingPolicy` script:

https://github.com/input-output-hk/plutus-apps/blob/710184bed3fb43687fe78c3c93a329a876bf0c6b/plutus-contract/src/Plutus/Contract/StateMachine/ThreadToken.hs#L46-L72

**Comment by michaelpj** [comment]
More precisely, `ownCurrencySymbol` only works from the minting policy itself. Here the minting policy just says "this validator must run", and the validator can't ask for `ownCurrencySymbol` (because it's not a minting policy). If you need to communicate the currency hash to the validator you need another way to do that. I thought we had an example of that somewhere...

**Comment by georgeos** [comment]
Great! Thanks for your answers, now it's clear that I need another way to validate the currency symbol.
