### ISSUE TITLE
Variable Var n is not bound

### ISSUE THREAD

**Issue by locallycompact** [input-output-hk/plutus-apps#342]
### Summary

Hi, this occurs sporadically. I can run thousands of model checks in succession and not experience this, but sometimes I will experience this error:

```where
  Standard Model Check:  FAIL (43.28s)
    *** Failed! (after 45 tests and 10 shrinks):
    Exception:
      Variable Var 14 is not bound!
      CallStack (from HasCallStack):
        error, called at src/Test/QuickCheck/StateModel.hs:75:18 in quickcheck-dynamic-0.1.0.0-KyLL9UuOfU2
5O9KQ5A71yO:Test.QuickCheck.StateModel
    Actions
     [tok3 := SetupTokens,
      tok8 := MintIdents (Wallet 1) ["plazlemff",""],
      Init (Wallet 1) (SymInstanceParams {ident = tok14.hk, assets = [tok3.A,tok3.C]})]
```

### Steps to reproduce the behavior

Unable to share code for this, but I will try and make a reproduction when I can.

### Actual Result

Error

### Expected Result

No error

### System info

NixOS

**Comment by MaximilianAlgehed** [comment]
As you can see from the error message you're trying to use a symbolic token that doesn't exist - you have `SymInstanceParams {ident = tok14.hk, ...}` but there is no `tok14` in the list of actions. This is because your precondition for your actions is missing a check to make sure that the tokens that are in your actions after shrinking actually exist. Unfortunately you have to code this check up yourself as there is currently no generic programming support for this - we are working on a fix for that. For reference, see the Uniswap example.

**Comment by locallycompact** [comment]
Thank you for explaining I'll try this.

**Comment by MaximilianAlgehed** [comment]
To be specific check out the following line:
https://github.com/input-output-hk/plutus-apps/blob/9b5aeea0bdac2784c22bdc8528720835e125fd0a/plutus-use-cases/test/Spec/Uniswap.hs#L241
Here we check that the tokens we trying to set up a swap for actually exist in the set of tokens we've created for this test. When running normal tests this is "obviously true" - we don't generate symbolic tokens that haven't been created by `createToken`. However, because a symbolic token is just a pair of basically an action number and a specific identifier within the action (an action can create more than one token) this check still needs to be there for shrinking to work properly. Specifically, your original counterexample may be something like `Actions [tok1 := SetupTokens, UseToken tok1.A, <do something else>]` and shrinking will try to remove individual actions, so you get `Actions [UseToken tok1.A, <do something else>]`. Here `tok1` is basically a pointer to a token that is created non-existen action (what was originally `SetupTokens`) and so this test is meaningless. To avoid this problem we need checks like the one I linked above to make sure that `tok1.A` is actually meaningful in this particular trace.

Now, in the future it would be very nice to be able to automate these checks and make sure that no actions are present that contain references to unbound tokens. One way to do this is to pose some SYB-like constraints on `Action model` to require it to give you all symbolic tokens in an action so that we can check this behind the scenes. I'll bump this to the top of my bugfixing prio list.

**Comment by MaximilianAlgehed** [comment]
Heads up @locallycompact a feature that makes this more ergonomic has just been merged to `main`. I think you should be able to get rid of some of your wellformedness checks here now!

**Comment by locallycompact** [comment]
This is wonderful I'll try this now. Thank you.

**Comment by locallycompact** [comment]
I can't actually locate that plutus commit you used 4127e9cd6e889824d724c30eae55033cb50cbf3e

**Comment by MaximilianAlgehed** [comment]
You have to use `release/node-1.34` - that's the version of `plutus` that `plutus-apps` depends on.

**Comment by MaximilianAlgehed** [comment]
Ping @sjoerdvisscher as I don't quite understand how this is organized in separate projects.

**Comment by locallycompact** [comment]
I'm using a haskell.nix stack.yaml conversion. This works now: 

https://gitlab.homotopic.tech/plutus/contracts/nft/-/blob/master/stack.yaml

**Comment by locallycompact** [comment]
This was after adding a Data instance to SymValue, which I needed to compile the model. Not sure if that's relevant. I'll try and put together some open source examples.

**Comment by MaximilianAlgehed** [comment]
There is probably a bug in your generator. I would start by carefully going
through every use of `elements` to make sure you're not using it on an
empty list.

Secondly, the error you're getting (that the exception happened during
shrinking) is likely related to laziness. Perhaps your property is failing
(its definitely failing, and it most likely was failing before too - I
don't think recent changes should have changed that) and some part of the
input that wasn't evaluated when the property failed was evaluated during
shrinking.

**Comment by locallycompact** [comment]
I'm not experiencing model failures before I switch to the new version and I get this one now with the new version. I'll try and dig in.

**Comment by locallycompact** [comment]
Ok, I think I know the reason. Previously the precondition was being evaluated against the ModelState eagerly first before constructing the Action lazily later, so the precondition was firing before the call to elements, so I did have a bug, which was incidentally a bug previously in plutus-apps.

**Comment by MaximilianAlgehed** [comment]
Ah, that makes total sense. The new precondition is a lot stricter in the
action than the old precondition.
