### ISSUE TITLE
Why doesn't EmulatorTrace use the ledger rules?

### ISSUE THREAD

**Issue by L-as** [input-output-hk/plutus-apps#611]
### Describe the feature you'd like

Sorry for my ignorance, but it's not clear to me why EmulatorTrace reimplements the ledger rather than using the real ledger code from https://github.com/input-output-hk/cardano-ledger.

**Comment by ak3n** [comment]
As I understand, it's historically. And sometimes, to my taste, it might be too tedious to work directly with cardano-api types.

The plan is to switch fully to cardano-ledger (and cardano-api).

**Comment by koslambrou** [comment]
To continue's @ak3n 's answer, it's because the Emulator (with the ledger rules) was implemented **before** cardano-ledger integrated Alonzo era. We have to do that in order to be able write the plutus-apps framework for writing Plutus contracts. Now that the cardano-ledger implemented the rules, we should definitely switch to using it instead of our own.

By the way, our Emulator **is** using the real code in addition to our reimplementation. So, basically, the emulator does use the real ledger validation rules.

**Comment by koslambrou** [comment]
I meant that we're using the cardano-ledger rules for validating transactions that are submitted in the emulator. But you're right, for constructing the ScriptContext, we're not. We plan on doing it soon.

**Comment by ak3n** [comment]
Fixed in #642.
