### ISSUE TITLE
`cardano-node` can't sync with the public testnet when following testnet round-trip instructions

### ISSUE THREAD

**Issue by silky** [input-output-hk/plutus-apps#86]
## Summary

In the instructions on [testing the PAB round-trip on the public testnet](https://github.com/input-output-hk/plutus-apps/tree/main/plutus-pab/test-node), step 2 now fails due to a version mismatch with `cardano-node`.

## Steps to reproduce

1. Run up to "Step 2" of the [testnet testing instructions](https://github.com/input-output-hk/plutus-apps/tree/main/plutus-pab/test-node).
2. Observe that the node stops syncing with an error like:

```
[...:cardano.node.ChainDB:Error:46] [2021-11-08 08:08:52.46 UTC] Invalid block 2fbd8c97cb0643a879564f6fe42c4710486b636c1876a0c454ae8ea202c87d26 at slot 41763999: ExtValidationErrorLedger (
    HardForkLedgerErrorFromEra S (
      S (
        S (
          S (
            Z (
              WrapLedgerErr {
                unwrapLedgerErr = BBodyError (
                  BlockTransitionError [
                    ShelleyInAlonzoPredFail (
                      LedgersFailure (
                        LedgerFailure (
                          UtxowFailure (
                            WrappedShelleyEraFailure (
                              UtxoFailure (
                                UtxosFailure (
                                  ValidationTagMismatch (IsValid True) (
                                    FailedUnexpectedly [
                                      PlutusFailure "\nThe 2 arg plutus script (
                                        PlutusScript PlutusV1 ScriptHash \"8fd8fe8fce219f0ac0f71aa5afd3c98d4ff8c0ccea1c5882852b7914\"
                                    ) fails.\nCekError An error has occurred:  User error:\nThe budget was overspent. Final negative state: ({ cpu: -35982 | mem: 0 })\nThe redeemer is: List []\nThe context is:\nPurpose: Minting 8fd8fe8fce219f0ac0f71aa5afd3c98d4ff8c0ccea1c5882852b7914\nTxInfo:\n  TxId: ecee1d36dc6f4df7e731deba70e14aa51fade20b01aca8089667fc76ba388ba9\n  Inputs: [
```

## Expected behavior

The sync to work.

## Additional context

The problem is due to a mismatch between `cardano-node` versions. A fix is to obtain cardano-node the executable from `nix` instead of building it from our source, which has newer dependencies; which causes the mismatch.

**Comment by raduom** [comment]
There is actually a very easy fix. Use a different node version. What I am doing is, I have a checkout of `cardano-node` and I start the node from that shell and it can fully synchronise with the network, from there all the steps should still work.

**Comment by woofpool** [comment]
Can we run the 1.31.0 tag cardano-node exe and it’s associated testnet config files as a workaround?  I realize beta release of plutus-pab has dependencies on certain cardano node dep, but will the beta pab services work with testnet using latest cardano-node release?

**Comment by raduom** [comment]
That is odd. There is no binary added by nix in the current build. Maybe you have been using a `cardano-client` that was not provided by the `nix-shell`?

**Comment by woofpool** [comment]
> That is odd. There is no binary added by nix in the current build. Maybe you have been using a `cardano-client` that was not provided by the `nix-shell`?

I'm not a nix expert, but I looked through the nix package info in the project, and found
https://github.com/input-output-hk/plutus-apps/blob/main/nix/pkgs/haskell/materialized-linux/.plan.nix/cardano-node.nix#L14
This points at 1.30.0 for `cardano-node`.  Instead of using a nix build, I just checked out the 1.30.0 tag and built it with cabal/GHC.  Using this version of `cardano-node` allows me to sync the testnet with the config files under `plutus-pab/test-node/testnet'.

**Comment by raduom** [comment]
> > That is odd. There is no binary added by nix in the current build. Maybe you have been using a `cardano-client` that was not provided by the `nix-shell`?
> 
> I'm not a nix expert, but I looked through the nix package info in the project, and found https://github.com/input-output-hk/plutus-apps/blob/v2021-11-05/nix/pkgs/haskell/materialized-linux/.plan.nix/cardano-node.nix#L14 This points at 1.30.0 for `cardano-node`. Instead of using a nix build, I just checked out the 1.30.0 tag and built it with cabal/GHC. Using this version of `cardano-node` allows me to sync the testnet with the config files under `plutus-pab/test-node/testnet`.

Yes. That makes a lot of sense. We've updated the README.md file for node testing to ask people do exactly what you did to install `cardano-node`.

**Comment by raduom** [comment]
@silky I think we can close this one, unless there is anything else you wish to add.

**Comment by woofpool** [comment]
I'm still confused about the root issue described as a version mismatch.  It would be helpful to get a more detailed explanation.  Looking at the `cabal.project` file, I see the `source-repository-package` definition for `cardano-node`.  That tag is pointing at: https://github.com/input-output-hk/cardano-node/commit/b6ca519f97a0e795611a63174687e6bb70c9f752

Running this version of `cardano-node` causes a sync failure on a block containing a plutus script tx having to do with "budget overspent".  What I'm understanding (based on comment by silky above) is that the commit ID `b6ca519` of `cardano-node` is a newer version than the `cardano-node` software used to process testnet transactions.  So, if we use that version of `cardano-node` instead of `1.31.0` or even something slightly older like `1.30.0`, then it will fail to sync against testnet when it receives certain plutus script transactions.  Therefore, when `plutus-apps` PAB is released, I assume it will be accompanied by a new `cardano-node` release, and the client plutus-script transactions will need to be adjusted to fix this budget issue.  Is this explanation correct?

For testing the PAB beta release `v2021-11-05` tag, is there anything special about the node config files in `plutus-pab/test-node/testnet`?  Can we just grab the current node config files (https://hydra.iohk.io/build/7926804/download/1/index.html) and run the `1.31.0` tag of `cardano-node`?  I assume the `pab-config.yml` and `chain-index-config.json` files can be tweaked if necessary to make them work with latest deploy of node config files.

Thanks for your explanations, as this is rather confusing.

**Comment by raduom** [comment]
For the short story: if you use the 1.30.0+ node without using the `plutus-apps` nix-shell everything should work just fine.

The longer story...

The `plutus-apps` repository uses a newer version of `plutus` than the `cardano-node` repository does. In this new version (I assume) some more limitations have been placed on the amount of ADA required to process a transaction. When you build `cardano-node` from the `plutus-apps` repository it's `plutus` dependency is superseded by ours. So it looks like the version of `cardano-node` is the same as the one built from the `cardano-node` repository, but in reality the `plutus` dependency is much newer, and as such, untested yet. This newer, untested dependency, is what causes the issues.

Since we don't want to enforce using an older version of plutus for our dependency we decided to simply not provide `cardano-node` in our shell directly and ask our users to install it in some other way (we pointed them to the `cardano-node` README file). We may still decide that depending on an older version of plutus is a sensible thing to do, but as yet we have not had that conversation.

**Comment by woofpool** [comment]
I appreciate the nice explanation.  That clarifies things for me. The other question I had was about the node config files. Are the testnet node config files included in the directory `plutus-pab/test-node/testnet` important to use or can we just grab the ones for the latest deploy?

**Comment by raduom** [comment]
Downloading the latest node configurations is the best way to go about it (https://hydra.iohk.io/build/7366583/download/1/index.html). However at this point Hydra is down, so you may need to wait a bit for those :)

**Comment by woofpool** [comment]
Makes sense. Thanks
